# Generated by Django 4.1.7 on 2023-03-24 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='type',
            field=models.IntegerField(choices=[('karniz', 'karniz'), ('kalso', 'kalso'), ('karona', 'karona')]),
        ),
    ]
