# Generated by Django 4.1.4 on 2023-04-08 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bagetcolor',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='dashboard.baget'),
        ),
        migrations.AlterField(
            model_name='dori_apparat_color',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='dashboard.doriaparat'),
        ),
        migrations.AlterField(
            model_name='kalsocolor',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='dashboard.kalso'),
        ),
        migrations.AlterField(
            model_name='karnizcolor',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='dashboard.karniz'),
        ),
        migrations.AlterField(
            model_name='karonacolor',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='dashboard.karona'),
        ),
        migrations.AlterField(
            model_name='nojcolor',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='dashboard.noj'),
        ),
    ]
