# Generated by Django 4.1.7 on 2023-03-24 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_subcategory_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='category',
        ),
        migrations.AddField(
            model_name='character',
            name='student',
            field=models.ForeignKey(blank=True, limit_choices_to={1: 'karniz'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.subcategory'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='type',
            field=models.IntegerField(choices=[(1, 'karniz'), (2, 'kalso'), (3, 'karona')]),
        ),
    ]
