# Generated by Django 4.1.7 on 2023-03-24 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_character_category_character_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='student',
            field=models.ForeignKey(blank=True, limit_choices_to={1}, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.subcategory'),
        ),
    ]
