# Generated by Django 4.1.7 on 2023-03-24 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_character_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='student',
        ),
        migrations.AddField(
            model_name='character',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.subcategory'),
            preserve_default=False,
        ),
    ]
