# Generated by Django 4.1.7 on 2023-03-25 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_remove_character_student_character_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Character',
            new_name='Karniz',
        ),
    ]
