# Generated by Django 4.1.7 on 2023-03-25 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_rename_character_karniz'),
    ]

    operations = [
        migrations.AddField(
            model_name='karniz',
            name='material',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='karniz',
            name='razmer',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
