# Generated by Django 4.1.7 on 2023-03-25 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_karniz_material_karniz_razmer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karniz',
            name='category',
            field=models.ForeignKey(limit_choices_to={'type': 1}, on_delete=django.db.models.deletion.CASCADE, to='dashboard.subcategory'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='type',
            field=models.IntegerField(choices=[(1, 'karniz'), (2, 'kalso'), (3, 'karona'), (4, 'noj'), (5, 'baget'), (6, 'dori_aparat')]),
        ),
    ]
