# Generated by Django 4.1.7 on 2023-03-25 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_karniz_category_alter_subcategory_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kalso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('price', models.IntegerField()),
                ('brend', models.CharField(max_length=128)),
                ('quantity', models.IntegerField()),
                ('razmer', models.CharField(max_length=128)),
                ('material', models.CharField(max_length=128)),
                ('category', models.ForeignKey(limit_choices_to={'type': 1}, on_delete=django.db.models.deletion.CASCADE, to='dashboard.subcategory')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
