# Generated by Django 4.1.7 on 2023-03-26 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_kalso'),
    ]

    operations = [
        migrations.AddField(
            model_name='kalso',
            name='made_in',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kalso',
            name='size',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kalso',
            name='weight',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='karniz',
            name='made_in',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='karniz',
            name='size',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='karniz',
            name='weight',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kalso',
            name='category',
            field=models.ForeignKey(limit_choices_to={'type': 2}, on_delete=django.db.models.deletion.CASCADE, to='dashboard.subcategory'),
        ),
        migrations.CreateModel(
            name='Noj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('price', models.IntegerField()),
                ('brend', models.CharField(max_length=128)),
                ('made_in', models.CharField(max_length=128)),
                ('size', models.CharField(max_length=128)),
                ('weight', models.CharField(max_length=128)),
                ('quantity', models.IntegerField()),
                ('razmer', models.CharField(max_length=128)),
                ('material', models.CharField(max_length=128)),
                ('category', models.ForeignKey(limit_choices_to={'type': 4}, on_delete=django.db.models.deletion.CASCADE, to='dashboard.subcategory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Karona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('price', models.IntegerField()),
                ('brend', models.CharField(max_length=128)),
                ('made_in', models.CharField(max_length=128)),
                ('size', models.CharField(max_length=128)),
                ('weight', models.CharField(max_length=128)),
                ('quantity', models.IntegerField()),
                ('razmer', models.CharField(max_length=128)),
                ('material', models.CharField(max_length=128)),
                ('category', models.ForeignKey(limit_choices_to={'type': 3}, on_delete=django.db.models.deletion.CASCADE, to='dashboard.subcategory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DoriAparat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('price', models.IntegerField()),
                ('brend', models.CharField(max_length=128)),
                ('made_in', models.CharField(max_length=128)),
                ('size', models.CharField(max_length=128)),
                ('weight', models.CharField(max_length=128)),
                ('quantity', models.IntegerField()),
                ('razmer', models.CharField(max_length=128)),
                ('material', models.CharField(max_length=128)),
                ('category', models.ForeignKey(limit_choices_to={'type': 2}, on_delete=django.db.models.deletion.CASCADE, to='dashboard.subcategory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Baget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('price', models.IntegerField()),
                ('brend', models.CharField(max_length=128)),
                ('made_in', models.CharField(max_length=128)),
                ('size', models.CharField(max_length=128)),
                ('weight', models.CharField(max_length=128)),
                ('quantity', models.IntegerField()),
                ('razmer', models.CharField(max_length=128)),
                ('material', models.CharField(max_length=128)),
                ('category', models.ForeignKey(limit_choices_to={'type': 2}, on_delete=django.db.models.deletion.CASCADE, to='dashboard.subcategory')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
