# Generated by Django 4.1.7 on 2023-03-26 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_kalso_made_in_kalso_size_kalso_weight_karniz_made_in_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baget',
            old_name='made_in',
            new_name='made_in_ru',
        ),
        migrations.RenameField(
            model_name='baget',
            old_name='name',
            new_name='made_in_uz',
        ),
        migrations.RenameField(
            model_name='doriaparat',
            old_name='made_in',
            new_name='made_in_ru',
        ),
        migrations.RenameField(
            model_name='doriaparat',
            old_name='name',
            new_name='made_in_uz',
        ),
        migrations.RenameField(
            model_name='kalso',
            old_name='made_in',
            new_name='made_in_ru',
        ),
        migrations.RenameField(
            model_name='kalso',
            old_name='name',
            new_name='made_in_uz',
        ),
        migrations.RenameField(
            model_name='karniz',
            old_name='made_in',
            new_name='made_in_ru',
        ),
        migrations.RenameField(
            model_name='karniz',
            old_name='material',
            new_name='made_in_uz',
        ),
        migrations.RenameField(
            model_name='karniz',
            old_name='name',
            new_name='material_ru',
        ),
        migrations.RenameField(
            model_name='karona',
            old_name='made_in',
            new_name='made_in_ru',
        ),
        migrations.RenameField(
            model_name='karona',
            old_name='name',
            new_name='made_in_uz',
        ),
        migrations.RenameField(
            model_name='noj',
            old_name='made_in',
            new_name='made_in_ru',
        ),
        migrations.RenameField(
            model_name='noj',
            old_name='name',
            new_name='made_in_uz',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='content',
            new_name='content_ru',
        ),
        migrations.AddField(
            model_name='baget',
            name='material_ru',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='baget',
            name='material_uz',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='baget',
            name='name_ru',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='baget',
            name='name_uz',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doriaparat',
            name='material_ru',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doriaparat',
            name='material_uz',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doriaparat',
            name='name_ru',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doriaparat',
            name='name_uz',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kalso',
            name='material_ru',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kalso',
            name='material_uz',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kalso',
            name='name_ru',
            field=models.CharField(default=11, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kalso',
            name='name_uz',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='karniz',
            name='material_uz',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='karniz',
            name='name_ru',
            field=models.CharField(default=11, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='karniz',
            name='name_uz',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='karona',
            name='material_ru',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='karona',
            name='material_uz',
            field=models.CharField(default=11, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='karona',
            name='name_ru',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='karona',
            name='name_uz',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='noj',
            name='material_ru',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='noj',
            name='material_uz',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='noj',
            name='name_ru',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='noj',
            name='name_uz',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcategory',
            name='content_uz',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='baget',
            name='category',
            field=models.ForeignKey(limit_choices_to={'type': 5}, on_delete=django.db.models.deletion.CASCADE, to='dashboard.subcategory'),
        ),
        migrations.AlterField(
            model_name='doriaparat',
            name='category',
            field=models.ForeignKey(limit_choices_to={'type': 6}, on_delete=django.db.models.deletion.CASCADE, to='dashboard.subcategory'),
        ),
    ]
