# Generated by Django 4.1.7 on 2023-03-26 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_rename_made_in_baget_made_in_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doriaparat',
            name='img',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
