# Generated by Django 4.1.7 on 2023-03-26 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_doriaparat_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doriaparat',
            name='img',
        ),
        migrations.CreateModel(
            name='DoritImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='dashboard.doriaparat')),
            ],
        ),
    ]
