# Generated by Django 4.1.7 on 2023-03-28 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_baget_baguette_width_baget_capacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baget',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='doriaparat',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='kalso',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='karniz',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='karona',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='noj',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
