# Generated by Django 4.1.7 on 2023-03-30 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_baget_status_doriaparat_status_kalso_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noj',
            old_name='style_uz',
            new_name='style_uzstyle_uz',
        ),
        migrations.AddField(
            model_name='baget',
            name='description_ru',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='baget',
            name='description_uz',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doriaparat',
            name='description_ru',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doriaparat',
            name='description_uz',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
