# Generated by Django 4.1.7 on 2023-04-03 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='karniz',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.karniz'),
            preserve_default=False,
        ),
    ]
