# Generated by Django 4.1.7 on 2023-04-03 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_discount_karniz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='product_subctg_id',
        ),
        migrations.AddField(
            model_name='discount',
            name='baget',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.baget'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='discount',
            name='dori_apparat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.doriaparat'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='discount',
            name='kalso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.kalso'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='discount',
            name='karona',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.karona'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='discount',
            name='noj',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.noj'),
            preserve_default=False,
        ),
    ]
