# Generated by Django 4.1.7 on 2023-04-04 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='karniz',
            name='discount_price',
            field=models.IntegerField(null=True),
        ),
    ]
