# Generated by Django 4.1.7 on 2023-04-04 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_karniz_discount_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karniz',
            name='discount_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
