# Generated by Django 4.1.7 on 2023-04-04 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_alter_karniz_discount_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baget',
            name='status',
        ),
        migrations.RemoveField(
            model_name='doriaparat',
            name='status',
        ),
        migrations.RemoveField(
            model_name='kalso',
            name='status',
        ),
        migrations.RemoveField(
            model_name='karona',
            name='status',
        ),
        migrations.RemoveField(
            model_name='noj',
            name='status',
        ),
    ]
