# Generated by Django 4.1.7 on 2023-04-04 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_remove_baget_status_remove_doriaparat_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baget',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='doriaparat',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='kalso',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='karona',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='noj',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
