# Generated by Django 4.1.7 on 2023-04-04 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_baget_status_doriaparat_status_kalso_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baget',
            name='discount_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doriaparat',
            name='discount_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kalso',
            name='discount_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='karona',
            name='discount_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='noj',
            name='discount_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
