# Generated by Django 4.1.7 on 2023-04-06 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_baget_discount_price_doriaparat_discount_price_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Discount',
        ),
    ]
